image: openjdk:11-jre-slim

build:
  script:
    - mvn clean install

deploy:
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git
    - git push heroku master
  only:
    - master