image: openjdk:11-jre-slim

stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn install -B"

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master